local function show(...)
	local n = select("#", ...)
	local t = {}
	for i = 1, n do
		local v = select(i, ...)
		local ty = type(v)
		t[i] = (ty == "table" or ty == "function" or ty == "thread") and ty or tostring(v)
	end
	return table.concat(t, ", ")
end
function T(name, fn)
	local r = table.pack(pcall(fn))
	print(name .. ": " .. (r[1] and "" or "ERR ") .. show(table.unpack(r, 2, r.n)))
end

T("add", function() return 1 + 2 end)
T("sub", function() return 5 - 7 end)
T("mul", function() return 3 * 4.5 end)
T("div", function() return 7 / 2 end)
T("div0", function() return 1 / 0, -1 / 0 end)
T("idiv", function() return 7 // 2, -7 // 2, 7.5 // 2 end)
T("mod", function() return 7 % 3, -7 % 3, 7 % -3, -7 % -3, 5.5 % 2 end)
T("mod0", function() return 5 % 0 end)
T("pow", function() return 2 ^ 10, 2 ^ 0.5, (-8) ^ (1/3) end)
T("unm", function() return -5, - -5, -(-5) end)
T("prec1", function() return 2 + 3 * 4 ^ 2 / 8 end)
T("prec2", function() return -2 ^ 2 end)
T("prec3", function() return not nil == true end)
T("prec4", function() return 1 .. 2 .. 3 end)
T("prec5", function() return 2 ^ 3 ^ 2 end)
T("prec6", function() return 1 + 2 < 4 and "y" or "n" end)
T("concat_num", function() return 1 .. "" , 1.5 .. "x", -0 .. "" end)
T("str_arith", function() return "10" + 5, "3" * "4", 10 .. "" + 1 end)
T("str_arith_bad", function() return "abc" + 1 end)
T("cmp_num", function() return 1 < 2, 2 <= 2, 3 > 4, 3 >= 3, 1 == 1.0, 1 ~= 2 end)
T("cmp_str", function() return "a" < "b", "abc" < "abd", "Z" < "a", "" < "a", "a" <= "a" end)
T("cmp_mixed", function() return 1 < "2" end)
T("cmp_nil", function() return nil < 1 end)
T("cmp_tbl", function() return {} < {} end)
T("eq_types", function() return 1 == "1", nil == false, {} == {}, "a" == "a" end)
T("eq_nan", function() local n = 0/0 return n == n, n ~= n end)
T("and_or", function() return 1 and 2, nil and 2, false or 3, nil or false, 0 and "zero", "" and "empty" end)
T("and_or_chain", function() local x = nil return x and x.y or "default" end)
T("not", function() return not nil, not false, not 0, not "", not {} end)
T("len_str", function() return #"hello", #"", #"héllo" end)
T("len_tbl", function() return #{1, 2, 3}, #{}, #{n = 1}, #{1, 2, nil, 4} end)
T("len_nil", function() return #nil end)
T("tostring_num", function() return tostring(10), tostring(1.5), tostring(-0.0), tostring(1e100), tostring(2^53), tostring(0.1) end)
T("tostring_big", function() return 1e15, 1e16, 123456789012345, 0.1 + 0.2, 1/3 end)
T("tostring_exp", function() return 1e-5, 1e-7, 5e-324, 1e300 * 10, 2^63 end)
T("tonumber", function() return tonumber("10"), tonumber("0x1F"), tonumber(" 5 "), tonumber("5."), tonumber(".5"), tonumber("1e2") end)
T("tonumber_bad", function() return tonumber("abc"), tonumber(""), tonumber("1 2"), tonumber(nil), tonumber({}) end)
T("tonumber_base", function() return tonumber("ff", 16), tonumber("101", 2), tonumber("zz", 36), tonumber("8", 8), tonumber("-10", 2) end)
T("type", function() return type(1), type("s"), type(nil), type({}), type(print), type(true), type(coroutine.create(print)) end)
T("typeof", function() return typeof(1), typeof({}), typeof(nil) end)
T("math_float_int", function() return 3 == 3.0, 2^31, 2^32 + 1, 1e3 end)
T("hex_bin_literals", function() return 0xFF, 0b1010, 0XaB, 1_000_000 end)
T("string_escapes", function() return "a\tb", "\65\066\x41", "\u{48}\u{20AC}", "a\z
        b", 'it\'s', "q\"q" end)
T("long_string", function() return [[line1
line2]], [==[a]]b]==], #[[
x]] end)
T("comment_forms", function() --[[ block ]] local x = 1 --[==[ another
multi ]==] return x end)
T("multiple_assign", function() local a, b, c = 1, 2 return a, b, c end)
T("swap", function() local a, b = 1, 2 a, b = b, a return a, b end)
T("multi_assign_eval", function() local t = {} local i = 1 i, t[i] = i + 1, 20 return i, t[1], t[2] end)
T("nested_tables", function() local t = {a = {b = {c = 42}}} return t.a.b.c, t["a"]["b"].c end)
T("global_assign", function() gx = 5 gx = gx + 1 return gx end)
T("global_nil", function() return undefinedglobal end)
T("shadow", function() local x = 1 do local x = x + 1 do local x = x * 10 end end return x end)
T("shadow2", function() local x = 1 local x = x + 1 return x end)
T("while_loop", function() local i, s = 0, 0 while i < 5 do i = i + 1 s = s + i end return s end)
T("repeat_scope", function() local n = 0 repeat local d = n n = n + 1 until d >= 3 return n end)
T("numfor", function() local s = 0 for i = 1, 10 do s = s + i end return s end)
T("numfor_step", function() local r = {} for i = 10, 1, -3 do r[#r + 1] = i end return table.concat(r, ",") end)
T("numfor_float", function() local r = {} for i = 0, 1, 0.25 do r[#r + 1] = i end return table.concat(r, ",") end)
T("numfor_empty", function() local c = 0 for i = 5, 1 do c = c + 1 end return c end)
T("numfor_var_copy", function() local r = {} for i = 1, 3 do r[#r + 1] = function() return i end i = i * 10 end return r[1](), r[2](), r[3]() end)
T("numfor_zero_step", function() for i = 1, 2, 0 do end end)
T("break", function() local s = 0 for i = 1, 100 do if i > 5 then break end s = s + i end return s end)
T("goto_free_continue", function() local s = 0 for i = 1, 10 do if i % 2 == 0 then continue end s = s + i end return s end)
T("continue_while", function() local i, s = 0, 0 while i < 10 do i += 1 if i % 3 ~= 0 then continue end s += i end return s end)
T("continue_repeat", function() local i, s = 0, 0 repeat i += 1 if i == 2 then continue end s += i until i >= 5 return s end)
T("nested_break", function() local c = 0 for i = 1, 3 do for j = 1, 3 do if j == 2 then break end c += 1 end end return c end)
