local function show(...)
	local n = select("#", ...)
	local t = {}
	for i = 1, n do
		local v = select(i, ...)
		local ty = type(v)
		t[i] = (ty == "table" or ty == "function" or ty == "thread") and ty or tostring(v)
	end
	return table.concat(t, ", ")
end
function T(name, fn)
	local r = table.pack(pcall(fn))
	print(name .. ": " .. (r[1] and "" or "ERR ") .. show(table.unpack(r, 2, r.n)))
end

T("varargs_count", function() local function f(...) return select("#", ...) end return f(), f(nil), f(1, nil), f(nil, nil, nil) end)
T("varargs_pack", function() local function f(...) local t = {...} return #t, t[1], t[3] end return f(1, 2, 3) end)
T("varargs_forward", function() local function g(...) return ... end local function f(...) return g(...) end return f(1, 2, 3) end)
T("varargs_mid", function() local function f(...) return (...) end return f(7, 8, 9) end)
T("varargs_select_neg", function() return select(-1, 1, 2, 3), select(-2, 1, 2, 3) end)
T("select_pos", function() return select(2, "a", "b", "c") end)
T("select_bad", function() return select(0, 1) end)
T("multi_ret", function() local function f() return 1, 2, 3 end local a, b, c, d = f() return a, b, c, d end)
T("multi_trunc", function() local function f() return 1, 2, 3 end return (f()) end)
T("multi_mid", function() local function f() return 1, 2, 3 end return f(), f() end)
T("multi_table", function() local function f() return 1, 2, 3 end local t = {f(), f()} return #t end)
T("multi_args", function() local function f() return 1, 2 end return math.max(f()), math.max(f(), 10) end)
T("ret_none", function() local function f() end return select("#", f()) end)
T("ret_nil", function() local function f() return nil end return select("#", f()) end)
T("tail_call", function() local function f(n, acc) if n == 0 then return acc end return f(n - 1, acc + n) end return f(100, 0) end)
T("recursion_fib", function() local function fib(n) if n < 2 then return n end return fib(n - 1) + fib(n - 2) end return fib(20) end)
T("closure_counter", function() local function mk() local c = 0 return function() c += 1 return c end end local a, b = mk(), mk() a() a() return a(), b() end)
T("closure_shared", function() local function mk() local v = 0 return function() v += 1 return v end, function() return v end end local inc, get = mk() inc() inc() return get() end)
T("closure_loop", function() local fs = {} for i = 1, 3 do fs[i] = function() return i end end return fs[1](), fs[2](), fs[3]() end)
T("closure_while", function() local fs = {} local i = 0 while i < 3 do i += 1 local j = i fs[i] = function() return j end end return fs[1](), fs[2](), fs[3]() end)
T("closure_upvalue_mutation", function() local x = 1 local function f() return x end x = 2 return f() end)
T("method_call", function() local o = {n = 5} function o:get() return self.n end function o.static(a) return a end return o:get(), o.static(3) end)
T("method_str", function() return ("abc"):upper(), ("x"):rep(2) end)
T("method_on_nil", function() local o return o:foo() end)
T("call_nil", function() local f f() end)
T("call_number", function() local f = 5 f() end)
T("call_field_nil", function() local t = {} t.x() end)
T("call_method_nil", function() local t = {} t:nomethod() end)
T("fn_in_table", function() local t = {f = function(x) return x * 2 end} return t.f(4), t["f"](5) end)
T("fn_define_nested", function() local a = {b = {}} function a.b.c(x) return x + 1 end function a.b:d() return self == a.b end return a.b.c(1), a.b:d() end)
T("anon_call", function() return (function(a, b) return a + b end)(3, 4) end)
T("string_call", function() local function f(s) return "[" .. tostring(s) .. "]" end return f"x", f[[y]] end)
T("table_call", function() local function f(t) return #t end return f{1, 2, 3} end)
T("default_arg", function() local function f(a, b) b = b or 10 return a + b end return f(1), f(1, 2) end)
T("extra_args", function() local function f(a) return a end return f(1, 2, 3) end)
T("fn_equal", function() local f = function() end return f == f, f == function() end end)
T("pcall_ok", function() return pcall(function(...) return ... end, 1, 2) end)
T("pcall_err", function() return pcall(error, "msg", 0) end)
T("pcall_err_tbl", function() local ok, e = pcall(error, {code = 7}) return ok, type(e), e.code end)
T("pcall_nil", function() return pcall(nil) end)
T("xpcall", function() return xpcall(function() error("bad", 0) end, function(m) return "H:" .. m end) end)
T("xpcall_args", function() return xpcall(function(a, b) return a + b end, print, 3, 4) end)
T("error_level0", function() error("x", 0) end)
T("error_level1", function() error("x", 1) end)
T("error_level2", function() local function f() error("x", 2) end f() end)
T("error_noarg", function() error() end)
T("error_nonstring", function() error(42) end)
T("error_table_pcall", function() local ok, e = pcall(error, setmetatable({}, {__tostring = function() return "custom" end})) return ok, tostring(e) end)
T("assert_ok", function() return assert(1, "m"), assert("v") end)
T("assert_fail", function() assert(false) end)
T("assert_msg", function() assert(nil, "custom message") end)
T("assert_tbl", function() local ok, e = pcall(assert, false, {1}) return ok, type(e) end)
T("nested_pcall", function() return pcall(pcall, error, "x") end)
T("pcall_returns_all", function() return pcall(function() return 1, nil, 3 end) end)
T("error_rethrow", function() local ok, e = pcall(function() local ok, e = pcall(error, "inner", 0) error(e .. "!", 0) end) return e end)
T("stackoverflow", function() local function f() return f() + 1 end local ok, e = pcall(f) return ok, type(e) end)
T("deep_recursion_ok", function() local function f(n) if n == 0 then return 0 end return 1 + f(n - 1) end return f(500) end)
T("unpack", function() return table.unpack({1, 2, 3}) end)
T("unpack_range", function() return table.unpack({1, 2, 3, 4}, 2, 3) end)
T("unpack_nil_holes", function() return select("#", table.unpack({1, nil, 3}, 1, 3)) end)
T("pack", function() local p = table.pack(1, nil, 3) return p.n, p[1], p[2], p[3] end)
T("fn_type", function() return type(function() end), type(print), type(string.rep) end)
T("recursive_local", function() local function fact(n) return n <= 1 and 1 or n * fact(n - 1) end return fact(10) end)
T("mutual_recursion", function() local isodd local function iseven(n) if n == 0 then return true end return isodd(n - 1) end function isodd(n) if n == 0 then return false end return iseven(n - 1) end return iseven(10), isodd(7) end)
T("vararg_in_table_mid", function() local function f(...) return {..., "end"} end return #f(1, 2, 3) end)
T("vararg_nil_args", function() local function f(...) local a, b = ... return a, b end return f(nil, 5) end)
T("select_hash_nil", function() return select("#", nil, nil) end)
T("pass_nil_middle", function() local function f(a, b, c) return a, b, c end return f(1, nil, 3) end)
