local function show(...)
	local n = select("#", ...)
	local t = {}
	for i = 1, n do
		local v = select(i, ...)
		local ty = type(v)
		t[i] = (ty == "table" or ty == "function" or ty == "thread") and ty or tostring(v)
	end
	return table.concat(t, ", ")
end
function T(name, fn)
	local r = table.pack(pcall(fn))
	print(name .. ": " .. (r[1] and "" or "ERR ") .. show(table.unpack(r, 2, r.n)))
end

T("len", function() return string.len("abc"), ("abc"):len(), #"abc" end)
T("sub1", function() return ("hello"):sub(2, 4), ("hello"):sub(2), ("hello"):sub(-3), ("hello"):sub(-3, -2) end)
T("sub_oob", function() return ("hello"):sub(0), ("hello"):sub(10), ("hello"):sub(3, 2), ("hello"):sub(-100, 2), ("hello"):sub(2, 100) end)
T("upper_lower", function() return ("Hello World"):upper(), ("Hello World"):lower() end)
T("rep", function() return ("ab"):rep(3), ("ab"):rep(0), ("ab"):rep(2, "-"), ("x"):rep(1, "-") end)
T("reverse", function() return ("abc"):reverse(), (""):reverse() end)
T("byte", function() return ("ABC"):byte(), ("ABC"):byte(2), ("ABC"):byte(1, 3), ("ABC"):byte(10) end)
T("char", function() return string.char(72, 105), string.char() end)
T("char_bad", function() return string.char(300) end)
T("byte_char_roundtrip", function() local s = "héllo wörld" local t = {} for i = 1, #s do t[i] = s:byte(i) end return string.char(table.unpack(t)) == s, #s end)
T("concat_ops", function() local s = "a" s = s .. "b" .. "c" s ..= "d" return s end)
T("compare", function() return "abc" == "abc", "abc" ~= "abd", "a" < "b", "B" < "a", "abc" < "abcd" end)
T("tostring_tonumber", function() return tostring(12), tonumber("12") + 1, "5" * 2, 5 .. "" end)
T("split1", function() local r = ("a,b,c"):split(",") return #r, r[1], r[3] end)
T("split_default", function() local r = ("a,b,,c"):split(",") return #r, r[3] == "" end)
T("split_empty_sep", function() local r = ("abc"):split("") return #r, r[2] end)
T("split_multi", function() local r = ("a--b--c"):split("--") return #r, r[2] end)
T("find_plain", function() return ("a.b.c"):find(".", 1, true), ("abc"):find("b", 1, true), ("abc"):find("x", 1, true) end)
T("find_init", function() return ("abcabc"):find("b", 3), ("abcabc"):find("b", -2), ("abc"):find("", 10), ("abc"):find("", 4) end)
T("find_empty", function() return ("abc"):find(""), ("abc"):find("", 2) end)
T("format_basic", function() return string.format("%d %s %5.1f", 42, "hi", 3.14159) end)
T("format_pct", function() return string.format("100%%"), string.format("%5s|%-5s|", "ab", "ab") end)
T("format_int_flags", function() return string.format("%05d|%+d|% d|%-4d|", 42, 42, 42, 42) end)
T("format_hex", function() return string.format("%x %X %#x %08x %o", 255, 255, 255, 255, 8) end)
T("format_float", function() return string.format("%f|%.2f|%10.3f|%-10.1f|", 1.5, 1.005, 3.14159, 2.5) end)
T("format_exp", function() return string.format("%e|%.2e|%E", 12345.6789, 0.00012, 5) end)
T("format_g", function() return string.format("%g|%g|%g|%g|%.3g|%g", 100000, 1000000, 0.0001, 0.00001, 1234.5678, 1.5) end)
T("format_s_tostring", function() return string.format("%s %s %s %s", nil, true, 12, {} ~= nil) end)
T("format_s_prec", function() return string.format("%.3s|%5.2s|", "abcdef", "xyz") end)
T("format_c", function() return string.format("%c%c%c", 76, 117, 97) end)
T("format_q", function() return string.format("%q", 'he said "hi"\n') end)
T("format_i", function() return string.format("%i", 7) end)
T("format_float_as_int", function() return string.format("%d", 3.0) end)
T("format_bad_int", function() return string.format("%d", 3.5) end)
T("format_bad_arg", function() return string.format("%d", "x") end)
T("format_too_few", function() return string.format("%d %d", 1) end)
T("format_neg_hex", function() return string.format("%x", -1) end)
T("format_u", function() return string.format("%u", 42) end)
T("format_star_width", function() return string.format("%5d|%-8s|%8s|", 1, "ab", "cd") end)
T("format_round", function() return string.format("%.0f %.0f %.0f %.1f", 0.5, 1.5, 2.5, 0.05) end)
T("format_big", function() return string.format("%d", 2^53), string.format("%.0f", 1e15), string.format("%d", -2^31) end)
T("format_inf_nan", function() return string.format("%f %f", 1/0, -1/0), string.format("%d", 0) end)
T("format_tostring_meta", function() local t = setmetatable({}, {__tostring = function() return "T!" end}) return string.format("%s", t) end)
T("gsub_str", function() return ("hello world"):gsub("o", "0") end)
T("gsub_count", function() return ("aaa"):gsub("a", "b", 2) end)
T("gsub_pattern", function() return ("hello world"):gsub("%w+", "<%0>") end)
T("gsub_captures", function() return ("hello world"):gsub("(%w+) (%w+)", "%2 %1") end)
T("gsub_func", function() return ("1 2 3"):gsub("%d", function(d) return tonumber(d) * 2 end) end)
T("gsub_func_nil", function() return ("abc"):gsub("%w", function(c) if c == "b" then return "B" end end) end)
T("gsub_table", function() return ("$a and $b"):gsub("%$(%w+)", {a = "1", b = "2"}) end)
T("gsub_anchor", function() return ("aaa"):gsub("^a", "b") end)
T("gsub_empty_match", function() return ("abc"):gsub("", "-") end)
T("gsub_star", function() return ("abc"):gsub("x*", "-") end)
T("gsub_percent_escape", function() return ("a.b"):gsub("%.", "%%") end)
T("gsub_bad_repl", function() return ("abc"):gsub("b", "%2") end)
T("gsub_invalid_percent", function() return ("abc"):gsub("b", "%") end)
T("gsub_number_repl", function() return ("abc"):gsub("b", 5) end)
T("gsub_trim", function() return ("  hi  "):gsub("^%s+", ""):gsub("%s+$", "") end)
T("gmatch_words", function() local r = {} for w in ("the quick brown"):gmatch("%a+") do r[#r + 1] = w end return table.concat(r, "|") end)
T("gmatch_pairs", function() local r = {} for k, v in ("a=1, b=2"):gmatch("(%w+)=(%w+)") do r[#r + 1] = k .. v end return table.concat(r, "|") end)
T("gmatch_empty", function() local c = 0 for _ in ("abc"):gmatch("") do c += 1 end return c end)
T("gmatch_pos", function() local r = {} for p in ("abc"):gmatch("()b") do r[#r + 1] = p end return r[1] end)
T("tostring_embedded_zero", function() local s = "a\0b" return #s, s:byte(2), s == "a\0b" end)
T("str_index", function() return ("abc").len, ("abc").x end)
T("str_index_num", function() return ("abc")[1] end)
T("interp1", function() local n, s = 5, "x" return `n={n} s={s}` end)
T("interp2", function() return `{1 + 2} and {"a" .. "b"}`, `no interp` end)
T("interp_nested", function() local t = {a = 1} return `v={t.a} {`in{t.a}`}` end)
T("interp_escape", function() return `a\`b\{c`, `tab\t|` end)
T("interp_float", function() return `{1.5} {10 / 4} {2^53}` end)
T("utf8_len", function() return utf8.len("héllo"), utf8.len("日本語"), #"日本語" end)
T("utf8_char", function() return utf8.char(72, 228, 8364, 128512) end)
T("utf8_codepoint", function() return utf8.codepoint("héllo", 1, -1) end)
T("utf8_codes", function() local r = {} for p, c in utf8.codes("aé") do r[#r + 1] = p .. ":" .. c end return table.concat(r, ",") end)
T("utf8_offset", function() return utf8.offset("aéb", 3), utf8.offset("aéb", -1) end)
T("utf8_invalid", function() return utf8.len("\xff") end)
T("utf8_charpattern", function() local n = 0 for _ in ("aé日"):gmatch(utf8.charpattern) do n += 1 end return n end)
