local function show(...)
	local n = select("#", ...)
	local t = {}
	for i = 1, n do
		local v = select(i, ...)
		local ty = type(v)
		t[i] = (ty == "table" or ty == "function" or ty == "thread") and ty or tostring(v)
	end
	return table.concat(t, ", ")
end
function T(name, fn)
	local r = table.pack(pcall(fn))
	print(name .. ": " .. (r[1] and "" or "ERR ") .. show(table.unpack(r, 2, r.n)))
end

T("class_a", function() return ("abc123"):match("%a+"), ("abc123"):match("%d+"), ("a b"):match("%s"), ("a,b"):match("%p") end)
T("class_w_x", function() return ("hello_world 99"):match("%w+"), ("zz1fF"):match("%x+"), ("AbC"):match("%u+"), ("AbC"):match("%l+") end)
T("class_neg", function() return ("abc123"):match("%A+"), ("abc 123"):match("%S+"), ("abc123"):match("%D+") end)
T("class_c_g", function() return ("a\1b"):match("%c"):byte(), ("a b"):match("%g+") end)
T("dot", function() return ("abc"):match("."), ("abc"):match("..."), ("a\nb"):match("a.b") end)
T("star_plus_q", function() return ("aaab"):match("a*"), ("b"):match("a*"), ("aaab"):match("a+"), ("b"):match("a+"), ("ab"):match("a?b"), ("b"):match("a?b") end)
T("lazy", function() return ("<<a>><<b>>"):match("<<(.-)>>"), ("aaa"):match("a-"), ("aaab"):match("a-b") end)
T("greedy_backtrack", function() return ("abcabc"):match("(.*)c"), ("abcabc"):match("(.+)b") end)
T("anchors", function() return ("abc"):match("^a"), ("abc"):match("^b"), ("abc"):match("c$"), ("abc"):match("b$"), ("a$b"):match("a$b") end)
T("sets", function() return ("hello"):match("[aeiou]"), ("hello"):match("[^aeiou]+"), ("a-b"):match("[a%-]+"), ("x5"):match("[%d]"), ("]"):match("[]]") end)
T("set_ranges", function() return ("Hello"):match("[a-z]+"), ("Hello"):match("[A-Z]"), ("x9"):match("[0-9]"), ("a-z"):match("[a-]+") end)
T("set_classes", function() return ("ab12"):match("[%a%d]+"), ("a_b"):match("[%w_]+"), ("a b"):match("[^%s]+") end)
T("captures", function() return ("2024-01-15"):match("(%d+)-(%d+)-(%d+)") end)
T("capture_nested", function() return ("abc"):match("((a)(b))c") end)
T("capture_pos", function() return ("hello"):match("()ll()") end)
T("capture_empty", function() return ("abc"):match("()") end)
T("backref", function() return ("abcabc"):match("(abc)%1"), ("hello"):match("(l)%1"), ("abab"):match("(a)(b)%1%2") end)
T("balance", function() return ("f(a(b)c)d"):match("%b()"), ("[[x]]"):match("%b[]"), ("no"):match("%b()") end)
T("frontier", function() return ("THE (quick) fox"):find("%f[%a]%a+%f[%A]"), ("hello world"):gsub("%f[%w]%w+", string.upper) end)
T("find_captures", function() return ("hello world"):find("(o) (w)") end)
T("find_anchor_init", function() return ("abc"):find("^b", 2), ("abc"):find("^a", 2) end)
T("match_init", function() return ("abcabc"):match("a", 2), ("abcabc"):match("(b)", 3), ("abc"):match("b", -2) end)
T("special_escape", function() return ("a+b"):find("+", 1, true), ("a+b"):match("a%+b"), ("1.5"):match("%d%.%d"), ("a^b"):match("a%^b") end)
T("pattern_minus", function() return ("a-b"):match("a%-b"), ("a--b"):match("a-b") end)
T("quantified_class", function() return ("  x"):match("^%s*(.-)%s*$"), ("key = value"):match("^(%w+)%s*=%s*(%w+)$") end)
T("trim", function() local function trim(s) return (s:gsub("^%s*(.-)%s*$", "%1")) end return "[" .. trim("  hi there  ") .. "]" end)
T("csv", function() local r = {} for f in ("a,b,,d"):gmatch("([^,]*)") do r[#r + 1] = f end return table.concat(r, "|") end)
T("camel", function() return (("hello_world_foo"):gsub("_(%a)", function(c) return c:upper() end)) end)
T("count_matches", function() local _, n = ("a b c d"):gsub("%a", "") return n end)
T("gsub_anchored_pattern", function() return ("hello"):gsub("^h", "H"), ("hello"):gsub("o$", "0") end)
T("bad_pattern_end", function() return ("a"):match("%") end)
T("bad_pattern_set", function() return ("a"):match("[a") end)
T("bad_pattern_capture", function() return ("a"):match("(a") end)
T("bad_pattern_close", function() return ("a"):match("a)") end)
T("bad_pattern_backref", function() return ("a"):match("%1") end)
T("bad_pattern_b", function() return ("a"):match("%b") end)
T("bad_pattern_f", function() return ("a"):match("%fa") end)
T("pattern_too_complex", function() return (("a"):rep(1000)):match(("a?"):rep(1000) .. ("a"):rep(1000)) ~= nil end)
T("long_input", function() local s = ("x"):rep(10000) return #s:gsub("x", "yy"), s:find("y") end)
T("unmatched", function() return ("abc"):match("xyz"), ("abc"):find("xyz"), ("abc"):gsub("xyz", "q") end)
T("multi_return_captures", function() local a, b, c = ("k=v;z"):match("(%w)=(%w);(%w)") return a, b, c end)
T("dot_star_greedy", function() return ("a.b.c"):match("^(.*)%.(.*)$") end)
T("lua_string_functions_chain", function() return ("  Hello  "):gsub("^%s+", ""):lower():upper():rep(2) end)
T("path_split", function() local p = "a/b/c.txt" return p:match("([^/]+)$"), p:match("^(.*)/"), p:match("%.(%w+)$") end)
T("number_extract", function() local r = {} for n in ("1, 22, -3.5, 4e2"):gmatch("-?%d+%.?%d*") do r[#r + 1] = tonumber(n) end return table.concat(r, " ") end)
T("case_insens", function() local function ci(p) return (p:gsub("%a", function(c) return "[" .. c:lower() .. c:upper() .. "]" end)) end return ("HeLLo"):match(ci("hello")) end)
T("gsub_repl_cap_pos", function() return ("abc"):gsub("()", "%1") end)
T("find_special_in_plain_find", function() return ("a(b"):find("("), ("a[b"):find("[") end)
