local function show(...)
	local n = select("#", ...)
	local t = {}
	for i = 1, n do
		local v = select(i, ...)
		local ty = type(v)
		t[i] = (ty == "table" or ty == "function" or ty == "thread") and ty or tostring(v)
	end
	return table.concat(t, ", ")
end
function T(name, fn)
	local r = table.pack(pcall(fn))
	print(name .. ": " .. (r[1] and "" or "ERR ") .. show(table.unpack(r, 2, r.n)))
end

T("ctor_array", function() local t = {10, 20, 30} return #t, t[1], t[3], t[4] end)
T("ctor_hash", function() local t = {a = 1, ["b c"] = 2, [3] = "x"} return t.a, t["b c"], t[3], #t end)
T("ctor_mixed", function() local t = {1, 2, x = "y", 3} return #t, t.x, t[3] end)
T("ctor_nested_sep", function() local t = {1; 2; 3} return #t end)
T("ctor_trailing", function() local t = {1, 2, 3,} return #t end)
T("ctor_nil_values", function() local t = {1, nil, 3} return #t, t[2], t[3] end)
T("ctor_nil_trailing", function() local t = {1, 2, nil} return #t end)
T("ctor_call_expand", function() local function f() return 1, 2, 3 end local t = {f()} local u = {f(), f()} local v = {(f())} return #t, #u, #v end)
T("ctor_expr_keys", function() local k = "dyn" local t = {[k] = 1, [k .. "2"] = 2, [1 + 1] = "two"} return t.dyn, t.dyn2, t[2] end)
T("ctor_dup_keys", function() local t = {a = 1, a = 2} return t.a end)
T("index_missing", function() local t = {} return t.x, t[1], t[true] end)
T("assign_nil_deletes", function() local t = {a = 1} t.a = nil local c = 0 for _ in pairs(t) do c += 1 end return c, t.a end)
T("len_after_append", function() local t = {} for i = 1, 10 do t[#t + 1] = i end return #t end)
T("len_after_remove", function() local t = {1, 2, 3} t[#t] = nil return #t end)
T("len_holes", function() local t = {} t[1] = 1 t[2] = 2 t[4] = 4 return #t == 2 or #t == 4 end)
T("len_reverse_fill", function() local t = {} t[3] = 3 t[2] = 2 t[1] = 1 return #t end)
T("float_keys", function() local t = {} t[1.0] = "a" t[2] = "b" t[1.5] = "c" return t[1], #t, t[1.5], t[2.0] end)
T("neg_zero_key", function() local t = {} t[0] = "z" t[-0] = "nz" return t[0] end)
T("nan_key_set", function() local t = {} t[0/0] = 1 end)
T("nan_key_get", function() local t = {} return t[0/0] end)
T("nil_key_set", function() local t = {} t[nil] = 1 end)
T("bool_keys", function() local t = {[true] = "t", [false] = "f"} return t[true], t[false] end)
T("table_keys", function() local k1, k2 = {}, {} local t = {[k1] = 1, [k2] = 2} return t[k1], t[k2], t[{}] end)
T("fn_keys", function() local f = function() end local t = {[f] = "fn"} return t[f] end)
T("insert_end", function() local t = {1, 2} table.insert(t, 3) table.insert(t, 4) return table.concat(t, ",") end)
T("insert_pos", function() local t = {1, 2, 3} table.insert(t, 1, 0) table.insert(t, 3, 99) return table.concat(t, ",") end)
T("insert_bad_args", function() table.insert({}, 1, 2, 3) end)
T("insert_nil_value", function() local t = {1} table.insert(t, nil) return #t end)
T("remove_end", function() local t = {1, 2, 3} local v = table.remove(t) return v, #t end)
T("remove_pos", function() local t = {1, 2, 3, 4} local v = table.remove(t, 2) return v, table.concat(t, ",") end)
T("remove_empty", function() return table.remove({}) end)
T("remove_first", function() local t = {"a", "b"} return table.remove(t, 1), t[1], #t end)
T("concat1", function() return table.concat({}), table.concat({1}), table.concat({1, 2, 3}), table.concat({"a", "b"}, ", ") end)
T("concat_range", function() return table.concat({1, 2, 3, 4}, "-", 2, 3), table.concat({1, 2}, "", 2, 1) end)
T("concat_float", function() return table.concat({1.5, 2, "x"}, " ") end)
T("concat_bad", function() return table.concat({1, {}, 3}) end)
T("sort_default", function() local t = {3, 1, 2} table.sort(t) return table.concat(t, ",") end)
T("sort_strings", function() local t = {"banana", "apple", "Cherry"} table.sort(t) return table.concat(t, ",") end)
T("sort_desc", function() local t = {1, 5, 3, 9, 2} table.sort(t, function(a, b) return a > b end) return table.concat(t, ",") end)
T("sort_records", function() local t = {{n = "b", v = 2}, {n = "a", v = 2}, {n = "c", v = 1}} table.sort(t, function(x, y) if x.v ~= y.v then return x.v < y.v end return x.n < y.n end) return t[1].n .. t[2].n .. t[3].n end)
T("sort_large", function() local t = {} for i = 1, 200 do t[i] = (i * 7919) % 211 end table.sort(t) for i = 2, #t do if t[i - 1] > t[i] then return false end end return true end)
T("sort_mixed_error", function() local t = {1, "a", 2} table.sort(t) end)
T("sort_single", function() local t = {5} table.sort(t) return t[1] end)
T("find1", function() return table.find({"a", "b", "c"}, "b"), table.find({"a"}, "z"), table.find({1, 2, 3}, 2, 3) end)
T("unpack_tbl", function() local a, b, c = table.unpack({1, 2, 3}) return a, b, c end)
T("pack_n", function() return table.pack().n, table.pack(nil).n, table.pack(1, 2).n end)
T("create", function() local t = table.create(3, 0) return #t, t[1], t[3] end)
T("clear", function() local t = {1, 2, a = 3} table.clear(t) return #t, t.a, next(t) end)
T("clone_shallow", function() local inner = {} local t = {inner, x = 1} local c = table.clone(t) c.x = 2 return t.x, c.x, c[1] == inner end)
T("clone_meta", function() local mt = {} local c = table.clone(setmetatable({}, mt)) return getmetatable(c) == mt end)
T("freeze", function() local t = table.freeze({1, 2}) return table.isfrozen(t), pcall(function() t[1] = 5 end) end)
T("freeze_insert", function() local t = table.freeze({1}) table.insert(t, 2) end)
T("isfrozen_false", function() return table.isfrozen({}) end)
T("move", function() local t = {1, 2, 3, 4, 5} table.move(t, 2, 4, 1) return table.concat(t, ",") end)
T("move_other", function() local a, b = {1, 2, 3}, {} table.move(a, 1, 3, 2, b) return b[1], b[2], b[4] end)
T("move_overlap", function() local t = {1, 2, 3, 4, 5} table.move(t, 1, 4, 2) return table.concat(t, ",") end)
T("pairs_all", function() local t = {10, 20, x = 1, y = 2} local n, s = 0, 0 for k, v in pairs(t) do n += 1 s += v end return n, s end)
T("pairs_order_array", function() local t = {5, 6, 7} local r = {} for k, v in pairs(t) do r[#r + 1] = k .. "=" .. v end return table.concat(r, ",") end)
T("ipairs_stop_nil", function() local r = {} for i, v in ipairs({1, 2, nil, 4}) do r[#r + 1] = v end return #r end)
T("ipairs_values", function() local s = 0 for i, v in ipairs({5, 6, 7}) do s += i * v end return s end)
T("generic_for_direct", function() local s = 0 for k, v in {1, 2, 3} do s += v end return s end)
T("next_empty", function() return next({}), next({}, nil) end)
T("next_iter", function() local t = {a = 1} local k, v = next(t) local k2 = next(t, k) return k, v, k2 end)
T("pairs_modify_existing", function() local t = {a = 1, b = 2, c = 3} for k, v in pairs(t) do t[k] = v * 2 end return t.a + t.b + t.c end)
T("pairs_delete_during", function() local t = {a = 1, b = 2, c = 3} for k in pairs(t) do t[k] = nil end return next(t) end)
T("rawget_rawset", function() local t = setmetatable({}, {__index = function() return "meta" end}) rawset(t, "x", 1) return rawget(t, "x"), rawget(t, "y"), t.y end)
T("rawequal_rawlen", function() local a = {} return rawequal(a, a), rawequal(a, {}), rawlen({1, 2}), rawlen("abc") end)
T("select_hash_tbl", function() local t = {n = 3} return select("#", table.unpack({1, 2, 3})), t.n end)
T("table_in_table_ref", function() local a = {} local b = {a} a[1] = b return a[1][1] == a end)
T("nested_len", function() local t = {{1, 2}, {3}} return #t, #t[1], #t[2] end)
T("array_of_arrays", function() local g = {} for i = 1, 3 do g[i] = {} for j = 1, 3 do g[i][j] = i * j end end return g[2][3], g[3][3] end)
T("table_equality", function() local a = {} local b = a return a == b, a == {}, {} ~= {} end)
T("length_operator_string_key", function() local t = {} t["1"] = "a" return #t, t[1], t["1"] end)
T("big_array", function() local t = {} for i = 1, 5000 do t[i] = i end local s = 0 for i = 1, #t do s += t[i] end return s end)
T("sparse_table", function() local t = {} t[1000000] = 1 t[1] = 1 return #t, t[1000000] end)
T("remove_shift_holes", function() local t = {1, 2, 3} t[2] = nil return #t, t[3] end)
T("unpack_with_nil_end", function() return select("#", table.unpack({1, 2, nil})) end)
T("table_getn_free", function() return #{n = 5} end)
T("tostring_table_prefix", function() return tostring({}):sub(1, 6), tostring(print):sub(1, 9) end)
