local function show(...)
	local n = select("#", ...)
	local t = {}
	for i = 1, n do
		local v = select(i, ...)
		local ty = type(v)
		t[i] = (ty == "table" or ty == "function" or ty == "thread") and ty or tostring(v)
	end
	return table.concat(t, ", ")
end
function T(name, fn)
	local r = table.pack(pcall(fn))
	print(name .. ": " .. (r[1] and "" or "ERR ") .. show(table.unpack(r, 2, r.n)))
end

T("index_table", function() local base = {greet = function() return "hi" end} local o = setmetatable({}, {__index = base}) return o.greet(), o.missing end)
T("index_fn", function() local o = setmetatable({}, {__index = function(t, k) return k .. "!" end}) return o.foo, o[1] end)
T("index_chain", function() local a = {x = 1} local b = setmetatable({y = 2}, {__index = a}) local c = setmetatable({}, {__index = b}) return c.x, c.y, c.z end)
T("index_raw_priority", function() local o = setmetatable({x = "own"}, {__index = {x = "base"}}) return o.x end)
T("newindex_fn", function() local log = {} local o = setmetatable({}, {__newindex = function(t, k, v) rawset(t, k, v * 2) end}) o.a = 5 return o.a end)
T("newindex_table", function() local store = {} local o = setmetatable({}, {__newindex = store}) o.a = 1 return rawget(o, "a"), store.a end)
T("newindex_existing", function() local called = 0 local o = setmetatable({a = 1}, {__newindex = function() called += 1 end}) o.a = 2 o.b = 3 return called, o.a end)
T("call_mm", function() local o = setmetatable({}, {__call = function(self, a, b) return a + b end}) return o(1, 2) end)
T("call_mm_varargs", function() local o = setmetatable({}, {__call = function(self, ...) return select("#", ...) end}) return o(), o(1, 2, 3) end)
T("tostring_mm", function() local o = setmetatable({}, {__tostring = function() return "custom!" end}) return tostring(o), "x" .. tostring(o) end)
T("tostring_bad_return", function() local o = setmetatable({}, {__tostring = function() return 1 end}) return tostring(o) end)
T("len_mm", function() local o = setmetatable({}, {__len = function() return 42 end}) return #o end)
T("eq_mm", function() local mt = {__eq = function(a, b) return a.v == b.v end} local a, b = setmetatable({v = 1}, mt), setmetatable({v = 1}, mt) return a == b, a ~= b, rawequal(a, b) end)
T("eq_mm_diff_types", function() local a = setmetatable({}, {__eq = function() return true end}) return a == 1, a == {} end)
T("lt_le_mm", function() local mt = {__lt = function(a, b) return a.v < b.v end, __le = function(a, b) return a.v <= b.v end} local a, b = setmetatable({v = 1}, mt), setmetatable({v = 2}, mt) return a < b, a > b, a <= b, a >= b end)
T("arith_mm", function() local mt = {} mt.__add = function(a, b) return "add" end mt.__sub = function() return "sub" end mt.__mul = function() return "mul" end mt.__div = function() return "div" end mt.__mod = function() return "mod" end mt.__pow = function() return "pow" end mt.__idiv = function() return "idiv" end mt.__unm = function() return "unm" end local o = setmetatable({}, mt) return o + 1, 1 - o, o * o, o / 2, o % 2, o ^ 2, o // 2, -o end)
T("concat_mm", function() local o = setmetatable({}, {__concat = function(a, b) return "cat" end}) return o .. "x", "x" .. o, 1 .. o end)
T("vector_class", function() local V = {} V.__index = V V.__add = function(a, b) return setmetatable({x = a.x + b.x}, V) end V.__tostring = function(v) return "V(" .. v.x .. ")" end function V.new(x) return setmetatable({x = x}, V) end function V:double() return V.new(self.x * 2) end return tostring(V.new(1) + V.new(2)), tostring(V.new(4):double()) end)
T("inheritance", function() local A = {} A.__index = A function A.new() return setmetatable({}, A) end function A:name() return "A" end function A:hello() return "hello from " .. self:name() end local B = setmetatable({}, {__index = A}) B.__index = B function B.new() return setmetatable({}, B) end function B:name() return "B" end return A.new():hello(), B.new():hello() end)
T("super_call", function() local A = {} A.__index = A function A:f() return "A.f" end local B = setmetatable({}, A) B.__index = B function B:f() return "B>" .. A.f(self) end return setmetatable({}, B):f() end)
T("getmetatable", function() local mt = {} local t = setmetatable({}, mt) return getmetatable(t) == mt, getmetatable({}), getmetatable("x").__index == string end)
T("metatable_protect", function() local t = setmetatable({}, {__metatable = "locked"}) return getmetatable(t), pcall(setmetatable, t, {}) end)
T("setmetatable_nil", function() local t = setmetatable({}, {}) setmetatable(t, nil) return getmetatable(t) end)
T("setmetatable_returns", function() local t = {} return setmetatable(t, {}) == t end)
T("rawget_bypass", function() local t = setmetatable({}, {__index = function() return 1 end}) return t.x, rawget(t, "x") end)
T("index_nil_meta_field", function() local t = setmetatable({}, {}) return t.x end)
T("proxy_readonly", function() local function ro(t) return setmetatable({}, {__index = t, __newindex = function() error("readonly", 2) end}) end local p = ro({a = 1}) return p.a, pcall(function() p.b = 2 end) end)
T("default_values", function() local t = setmetatable({}, {__index = function() return 0 end}) t.x += 1 t.y += 5 return t.x, t.y, t.z end)
T("counter_proxy", function() local n = 0 local t = setmetatable({}, {__index = function(_, k) n += 1 return k end}) local _ = t.a, t.b return n end)
T("class_tostring_in_print", function() local C = setmetatable({}, {__tostring = function() return "<C>" end}) return tostring(C), #tostring(C) end)
T("iter_mm", function() local o = setmetatable({}, {__iter = function() return function(_, i) if i < 3 then return i + 1 end end, nil, 0 end}) local r = {} for i in o do r[#r + 1] = i end return table.concat(r, ",") end)
T("call_chain", function() local o = setmetatable({}, {__call = function(self, x) return setmetatable({}, getmetatable(self)), x end}) local a, x = o(5) return x, getmetatable(a) == getmetatable(o) end)
T("index_depth", function() local t = {} for i = 1, 50 do t = setmetatable({}, {__index = t}) end return t.nothing end)
T("newindex_chain_table", function() local a = {} local b = setmetatable({}, {__newindex = a}) local c = setmetatable({}, {__newindex = b}) c.x = 1 return rawget(a, "x"), rawget(b, "x"), rawget(c, "x") end)
T("tostring_with_name", function() local t = setmetatable({}, {__type = "MyType"}) return typeof(t) end)
T("len_rawlen", function() local t = setmetatable({1, 2, 3}, {__len = function() return 10 end}) return #t, rawlen(t) end)
T("arith_on_mixed_mm", function() local mt = {__add = function(a, b) return (type(a) == "table" and a.v or a) + (type(b) == "table" and b.v or b) end} local o = setmetatable({v = 5}, mt) return o + 1, 1 + o, o + o end)
T("lt_mixed_error", function() local o = setmetatable({}, {}) return o < 1 end)
T("concat_error", function() return {} .. "x" end)
T("method_via_index_fn", function() local o = setmetatable({}, {__index = function(t, k) return function(self, a) return k .. a end end}) return o:foo("1"), o:bar("2") end)
