local function show(...)
	local n = select("#", ...)
	local t = {}
	for i = 1, n do
		local v = select(i, ...)
		local ty = type(v)
		t[i] = (ty == "table" or ty == "function" or ty == "thread") and ty or tostring(v)
	end
	return table.concat(t, ", ")
end
function T(name, fn)
	local r = table.pack(pcall(fn))
	print(name .. ": " .. (r[1] and "" or "ERR ") .. show(table.unpack(r, 2, r.n)))
end

T("basic", function() local co = coroutine.create(function(a, b) local c = coroutine.yield(a + b) local d, e = coroutine.yield(c * 2) return d + e end) local r = {} r[1] = select(2, coroutine.resume(co, 1, 2)) r[2] = select(2, coroutine.resume(co, 10)) r[3] = select(2, coroutine.resume(co, 3, 4)) return table.concat(r, ",") end)
T("status", function() local co co = coroutine.create(function() coroutine.yield() end) local s = {coroutine.status(co)} coroutine.resume(co) s[2] = coroutine.status(co) coroutine.resume(co) s[3] = coroutine.status(co) return table.concat(s, ",") end)
T("status_running", function() local co co = coroutine.create(function() return coroutine.status(co) end) return select(2, coroutine.resume(co)) end)
T("status_normal", function() local outer outer = coroutine.create(function() local inner = coroutine.create(function() return coroutine.status(outer) end) return select(2, coroutine.resume(inner)) end) return select(2, coroutine.resume(outer)) end)
T("resume_dead", function() local co = coroutine.create(function() end) coroutine.resume(co) return coroutine.resume(co) end)
T("resume_error", function() local co = coroutine.create(function() error("oops", 0) end) return coroutine.resume(co) end)
T("resume_error_table", function() local co = coroutine.create(function() error({code = 5}) end) local ok, e = coroutine.resume(co) return ok, e.code end)
T("error_kills", function() local co = coroutine.create(function() error("x", 0) end) coroutine.resume(co) return coroutine.status(co) end)
T("yield_values", function() local co = coroutine.create(function() coroutine.yield(1, 2, 3) end) return coroutine.resume(co) end)
T("yield_none", function() local co = coroutine.create(function() coroutine.yield() end) return select("#", coroutine.resume(co)) end)
T("return_values", function() local co = coroutine.create(function() return 1, 2 end) return coroutine.resume(co) end)
T("wrap_gen", function() local gen = coroutine.wrap(function() for i = 1, 3 do coroutine.yield(i) end end) return gen(), gen(), gen() end)
T("wrap_error", function() local f = coroutine.wrap(function() error("wrapped", 0) end) return pcall(f) end)
T("wrap_dead", function() local f = coroutine.wrap(function() end) f() return pcall(f) end)
T("wrap_args", function() local f = coroutine.wrap(function(a) local b = coroutine.yield(a * 2) return a + b end) return f(5), f(7) end)
T("generator_for", function() local function range(n) return coroutine.wrap(function() for i = 1, n do coroutine.yield(i) end end) end local s = 0 for i in range(5) do s += i end return s end)
T("producer_consumer", function() local prod = coroutine.create(function() for i = 1, 3 do coroutine.yield("item" .. i) end return "done" end) local out = {} while true do local ok, v = coroutine.resume(prod) out[#out + 1] = v if coroutine.status(prod) == "dead" then break end end return table.concat(out, ",") end)
T("yield_in_pcall", function() local co = coroutine.create(function() local ok, v = pcall(function() local x = coroutine.yield(1) error("after " .. x, 0) end) coroutine.yield(tostring(ok) .. ":" .. v) return "end" end) local a = select(2, coroutine.resume(co)) local b = select(2, coroutine.resume(co, "resume")) local c = select(2, coroutine.resume(co)) return a, b, c end)
T("yield_in_nested_calls", function() local function deep(n) if n == 0 then return coroutine.yield("bottom") end return deep(n - 1) end local co = coroutine.create(function() return deep(10) end) local a = select(2, coroutine.resume(co)) local b = select(2, coroutine.resume(co, "back")) return a, b end)
T("yield_in_metamethod", function() local o = setmetatable({}, {__index = function(t, k) return k end}) local co = coroutine.wrap(function() return o.hello end) return co() end)
T("isyieldable", function() local a = coroutine.isyieldable() local b local co = coroutine.wrap(function() b = coroutine.isyieldable() end) co() return a, b end)
T("running", function() local co co = coroutine.create(function() local c, main = coroutine.running() return c == co, main end) return select(2, coroutine.resume(co)) end)
T("running_main", function() local c, main = coroutine.running() return type(c), main end)
T("resume_self", function() local co co = coroutine.create(function() return coroutine.resume(co) end) return select(2, coroutine.resume(co)) end)
T("resume_non_thread", function() return coroutine.resume(5) end)
T("create_non_fn", function() return coroutine.create(5) end)
T("close_suspended", function() local co = coroutine.create(function() coroutine.yield() end) coroutine.resume(co) return coroutine.close(co), coroutine.status(co) end)
T("close_dead", function() local co = coroutine.create(function() end) coroutine.resume(co) return coroutine.close(co) end)
T("many_coroutines", function() local cos = {} for i = 1, 100 do cos[i] = coroutine.wrap(function() local x = i while true do x = x + coroutine.yield(x) end end) cos[i]() end local s = 0 for i = 1, 100 do s += cos[i](1) end return s end)
T("coroutine_closures", function() local function counter() local n = 0 return coroutine.wrap(function() while true do n += 1 coroutine.yield(n) end end) end local a, b = counter(), counter() a() a() return a(), b() end)
T("fibonacci_gen", function() local fib = coroutine.wrap(function() local a, b = 0, 1 while true do coroutine.yield(a) a, b = b, a + b end end) local r = {} for i = 1, 10 do r[i] = fib() end return table.concat(r, ",") end)
T("scheduler_roundrobin", function() local log = {} local tasks = {} for i = 1, 3 do tasks[i] = coroutine.create(function() for step = 1, 2 do log[#log + 1] = i .. ":" .. step coroutine.yield() end end) end for round = 1, 3 do for i = 1, 3 do if coroutine.status(tasks[i]) ~= "dead" then coroutine.resume(tasks[i]) end end end return table.concat(log, " ") end)
T("yield_across_table_sort", function() local co = coroutine.wrap(function() local t = {3, 1, 2} table.sort(t, function(a, b) coroutine.yield() return a < b end) end) return pcall(co) end)
T("yield_in_for_iter", function() local co = coroutine.wrap(function() for x in function() return coroutine.yield("iter") end do return x end end) local a = co() local b = co("val") return a, b end)
T("coroutine_error_position", function() local co = coroutine.create(function() local x = nil; return x.y end) return coroutine.resume(co) end)
T("traceback_string", function() return type(debug.traceback("msg")), debug.traceback("msg"):sub(1, 3) end)
