local function show(...)
	local n = select("#", ...)
	local t = {}
	for i = 1, n do
		local v = select(i, ...)
		local ty = type(v)
		t[i] = (ty == "table" or ty == "function" or ty == "thread") and ty or tostring(v)
	end
	return table.concat(t, ", ")
end
function T(name, fn)
	local r = table.pack(pcall(fn))
	print(name .. ": " .. (r[1] and "" or "ERR ") .. show(table.unpack(r, 2, r.n)))
end

T("floor_ceil", function() return math.floor(3.7), math.floor(-3.7), math.ceil(3.2), math.ceil(-3.2), math.floor(5), math.ceil(-0.5) end)
T("round_sign", function() return math.round(2.5), math.round(-2.5), math.round(2.4), math.round(0.5), math.sign(-3), math.sign(0), math.sign(7) end)
T("abs_sqrt", function() return math.abs(-5), math.abs(5), math.sqrt(16), math.sqrt(2), math.sqrt(-1) end)
T("minmax", function() return math.min(3, 1, 2), math.max(3, 1, 2), math.min(5), math.max(-1, -5) end)
T("pow_exp_log", function() return math.pow and "has pow" or "no pow", math.exp(0), math.log(1), math.log(8, 2), math.log(100, 10), math.log10(1000) end)
T("trig", function() return math.sin(0), math.cos(0), math.tan(0), math.floor(math.sin(math.pi / 2)), math.atan(1) * 4 == math.pi, math.atan2(1, 1) end)
T("trig_inv", function() return math.asin(1) * 2 == math.pi, math.acos(1), math.deg(math.pi), math.rad(180) == math.pi end)
T("fmod_modf", function() return math.fmod(7, 3), math.fmod(-7, 3), math.modf(3.7), math.modf(-3.7) end)
T("frexp_ldexp", function() return math.frexp(8), math.ldexp(0.5, 4), math.frexp(0) end)
T("clamp", function() return math.clamp(5, 1, 3), math.clamp(-1, 0, 10), math.clamp(2, 1, 3) end)
T("lerp", function() return math.lerp(0, 10, 0.5), math.lerp(5, 5, 1) end)
T("huge_pi", function() return math.huge, -math.huge, math.pi, math.huge == math.huge + 1 end)
T("random_range", function() math.randomseed(42) local ok = true for i = 1, 200 do local r = math.random(1, 6) if r < 1 or r > 6 or r ~= math.floor(r) then ok = false end end return ok end)
T("random_float", function() local ok = true for i = 1, 100 do local r = math.random() if r < 0 or r >= 1 then ok = false end end return ok end)
T("random_n", function() local ok = true for i = 1, 100 do local r = math.random(10) if r < 1 or r > 10 then ok = false end end return ok end)
T("random_empty", function() return math.random(5, 1) end)
T("float_precision", function() return 0.1 + 0.2 == 0.3, math.abs(0.1 + 0.2 - 0.3) < 1e-15, 1e15 + 1, 2^53 + 1 end)
T("int_division_semantics", function() return 7 // 0, -7 // 0, 0 // 0 ~= 0 // 0, 7 % math.huge, -7 % math.huge end)
T("big_numbers", function() return 2^1000 > 1e300, 2^-1074 > 0, 1e308 * 10 == math.huge end)
T("integer_check", function() return 5 // 1 == 5, 5.5 // 1, math.floor(5.5) == 5, 3 % 1 end)
T("num_to_str_coerce", function() return 10 .. "", 1e3 .. "", 0.5 .. "", (2^31) .. "" end)
T("tostring_negzero", function() return tostring(-0), tostring(0 * -1), 0 == -0 end)
T("bit_and_or_xor", function() return bit32.band(0xFF, 0x0F), bit32.bor(1, 2, 4), bit32.bxor(5, 3), bit32.bnot(0), bit32.band(), bit32.bor() end)
T("bit_shifts", function() return bit32.lshift(1, 4), bit32.rshift(256, 4), bit32.arshift(-16, 2), bit32.lshift(1, 31), bit32.lshift(1, 32), bit32.rshift(1, -3), bit32.lshift(1, -1) end)
T("bit_rotate", function() return bit32.lrotate(1, 1), bit32.rrotate(1, 1), bit32.lrotate(0x80000000, 1) end)
T("bit_extract", function() return bit32.extract(0xF0, 4, 4), bit32.extract(5, 0, 1), bit32.replace(0, 7, 4, 3) end)
T("bit_count", function() return bit32.countlz(1), bit32.countrz(8), bit32.countlz(0), bit32.countrz(0), bit32.btest(6, 3), bit32.btest(4, 3) end)
T("bit_wrap", function() return bit32.band(-1, 0xFFFFFFFF), bit32.bor(2^32 + 1, 0), bit32.bxor(0xFFFFFFFF, 1), bit32.byteswap(1) end)
T("os_time", function() local t = os.time() return type(t), t > 1600000000 end)
T("os_time_table", function() return os.time({year = 2020, month = 1, day = 1, hour = 0}) end)
T("os_date_fmt", function() return os.date("!%Y-%m-%d %H:%M:%S", 86400 * 365) end)
T("os_date_table", function() local d = os.date("!*t", 1000000000) return d.year, d.month, d.day, d.hour, d.min, d.sec, d.wday, d.yday end)
T("os_date_names", function() return os.date("!%A %B %d", 0), os.date("!%a %b", 0) end)
T("os_clock", function() local c = os.clock() return type(c), c >= 0 end)
T("os_difftime", function() return os.difftime(10, 4) end)
T("tick_free", function() return type(os.time()) end)
T("collectgarbage", function() return type(collectgarbage("count")) end)
T("select_neg_bounds", function() return select(-1, "a", "b"), pcall(select, -5, "a") end)
T("tostring_integers_big", function() return 2^53, 2^63, -2^63, 1e15, 123456789012 end)
T("string_number_compare", function() return "10" < "9", 10 < 9, "a" .. 1 < "a2" end)
T("numeric_for_float_accum", function() local c = 0 for i = 0.1, 1, 0.1 do c += 1 end return c end)
T("numeric_edge", function() return 1e308 + 1e308, -1e308 - 1e308, 5 // 0.3 end)
T("unary_minus_string", function() return -"2", - "0x10" end)
T("string_to_number_ops", function() return "0x10" + 0, "1e2" * 1, " 5 " + 0 end)
T("pow_neg", function() return 2 ^ -1, (-2) ^ 2, (-2) ^ 0.5 ~= (-2) ^ 0.5 end)
T("huge_loop_sum", function() local s = 0 for i = 1, 100000 do s += i % 7 end return s end)
