local function show(...)
	local n = select("#", ...)
	local t = {}
	for i = 1, n do
		local v = select(i, ...)
		local ty = type(v)
		t[i] = (ty == "table" or ty == "function" or ty == "thread") and ty or tostring(v)
	end
	return table.concat(t, ", ")
end
function T(name, fn)
	local r = table.pack(pcall(fn))
	print(name .. ": " .. (r[1] and "" or "ERR ") .. show(table.unpack(r, 2, r.n)))
end

T("compound_all", function() local a = 10 a += 5 a -= 3 a *= 2 a /= 4 a //= 2 a %= 4 a ^= 2 return a end)
T("compound_concat", function() local s = "a" s ..= "b" s ..= 1 return s end)
T("compound_field", function() local t = {n = 1, a = {b = 2}} t.n += 10 t.a.b *= 3 t["n"] -= 1 return t.n, t.a.b end)
T("compound_index_once", function() local calls = 0 local t = {5} local function idx() calls += 1 return 1 end t[idx()] += 1 return t[1], calls end)
T("compound_global", function() cg = 1 cg += 2 cg *= 5 return cg end)
T("compound_meta", function() local V = setmetatable({}, {__add = function(a, b) return "added" end}) local x = V x += 1 return x end)
T("if_expr", function() local x = 5 return if x > 3 then "big" else "small", if x > 10 then "huge" elseif x > 4 then "mid" else "tiny" end)
T("if_expr_nested", function() local function f(n) return if n < 0 then "neg" elseif n == 0 then "zero" else "pos" end return f(-1), f(0), f(1) end)
T("if_expr_falsy", function() return if nil then 1 else 2, if false then 1 else nil, if 0 then "zero-true" else "zero-false" end)
T("if_expr_noeval", function() local n = 0 local function f() n += 1 return n end local _ = if true then 1 else f() return n end)
T("type_annotations", function() local x: number = 5 local s: string = "a" local function f(a: number, b: string?): string return b or tostring(a) end return x, s, f(1), f(1, "z") end)
T("type_alias", function() type Point = {x: number, y: number} type Fn = (number) -> number local p: Point = {x = 1, y = 2} local f: Fn = function(n) return n * 2 end return p.x + p.y, f(4) end)
T("type_generic", function() type Box<T> = {value: T} local function id<T>(v: T): T return v end local b: Box<number> = {value = 5} return id(3), b.value end)
T("type_union_opt", function() local a: number | string = 5 local b: string? = nil local c: (number | nil) = 1 return a, b, c end)
T("type_cast", function() local x = (5 :: any) local y = ("s" :: string) return x, y, (nil :: any) end)
T("type_func_types", function() local f: (a: number, b: number) -> number = function(a, b) return a + b end local g: (...number) -> () = function(...) end return f(1, 2), g() end)
T("type_table_types", function() type T = {[string]: number} type A = {number} type M = {read x: number, write y: string} local t: T = {a = 1} local a: A = {1, 2} return t.a, #a end)
T("type_typeof", function() local a = 5 local b: typeof(a) = 6 return b end)
T("type_export", function() export type Foo = {a: number} local f: Foo = {a = 1} return f.a end)
T("type_intersection", function() type A = {a: number} type B = {b: number} type C = A & B local c: C = {a = 1, b = 2} return c.a + c.b end)
T("type_vararg_annot", function() local function f(...: number): number return select("#", ...) end return f(1, 2, 3) end)
T("type_for_annot", function() local s = 0 for i: number = 1, 3 do s += i end for k: string, v: number in {a = 1} do s += v end return s end)
T("type_return_pack", function() local function f(): (number, string) return 1, "a" end return f() end)
T("generic_fn_decl", function() local function map<T, U>(t: {T}, f: (T) -> U): {U} local r = {} for i, v in ipairs(t) do r[i] = f(v) end return r end return table.concat(map({1, 2, 3}, function(x) return x * 2 end), ",") end)
T("continue_ident", function() local continue = 5 return continue end)
T("continue_stmt_vs_call", function() local function continue() return "called" end return continue() end)
T("type_ident", function() local type = "shadowed" return type end)
T("type_ident_call", function() return type(5), type("x") end)
T("export_ident", function() local export = 3 return export end)
T("nested_functions", function() local function a() local function b() local function c() return "deep" end return c() end return b() end return a() end)
T("semicolons", function() local a = 1; local b = 2; return a + b; end)
T("long_comment_nested", function() --[==[ a ]] b ]==] return 1 end)
T("numeric_literals", function() return 0x10, 0xff, 1e2, 1E-2, .5, 5., 0b101, 1_0 end)
T("string_literal_forms", function() return 'single', "double", [[long]], [=[lvl1]=] end)
T("escapes_decimal", function() return "\104\105", "\x68\x69", "\u{68}\u{69}" end)
T("line_continuation", function() return "a\
b" end)
T("paren_call_ambig", function() local f = function() return function() return 1 end end return f()() end)
T("method_chain", function() local o = {v = 0} function o:add(n) self.v += n return self end return o:add(1):add(2):add(3).v end)
T("string_method_literal", function() return ("%d items"):format(3), #("abc"):rep(3) end)
T("table_method_decl", function() local M = {} M.sub = {} function M.sub.f(x) return x end function M.sub:g() return self == M.sub end return M.sub.f(1), M.sub:g() end)
T("multiple_returns_in_expr", function() local function f() return 1, 2 end local a, b, c = f(), 10 return a, b, c end)
T("assign_eval_order", function() local t = {} local i = 1 t[i], i = "a", 2 return t[1], t[2], i end)
T("global_function", function() function gfn(x) return x + 1 end return gfn(1), type(gfn) end)
T("global_table_fn", function() gtab = {} function gtab.f() return "gf" end function gtab:m() return self == gtab end return gtab.f(), gtab:m() end)
T("do_block_scope", function() local x = 1 do local x = 2 end return x end)
T("repeat_until_local_scope", function() local i = 0 repeat local done = i >= 2 i += 1 until done return i end)
T("while_with_break_and_continue", function() local i, r = 0, {} while true do i += 1 if i > 6 then break end if i % 2 == 0 then continue end r[#r + 1] = i end return table.concat(r, ",") end)
T("numeric_for_continue", function() local r = {} for i = 1, 5 do if i == 3 then continue end r[#r + 1] = i end return table.concat(r, ",") end)
T("generic_for_continue", function() local r = {} for i, v in ipairs({1, 2, 3, 4}) do if v % 2 == 1 then continue end r[#r + 1] = v end return table.concat(r, ",") end)
T("nested_continue", function() local c = 0 for i = 1, 3 do for j = 1, 3 do if j == 2 then continue end c += 1 end end return c end)
T("closure_in_loop_with_continue", function() local fs = {} for i = 1, 4 do if i % 2 == 0 then continue end fs[#fs + 1] = function() return i end end return fs[1](), fs[2]() end)
T("and_or_values", function() local a = nil local b = false local c = 0 return a or "d", b or "d", c or "d", a and 1, b and 1, c and 1 end)
T("comparison_chain_bool", function() local x = 5 return x > 1 and x < 10, x > 1 and x > 10, not (x == 5) end)
T("not_precedence", function() return not 1 == 2, not (1 == 2) end)
T("bool_ops_to_str", function() return tostring(1 < 2), tostring(not nil) end)
T("nested_ternary_like", function() local function f(x) return x == 1 and "one" or x == 2 and "two" or "many" end return f(1), f(2), f(3) end)
T("long_expr", function() return 1 + 2 * 3 - 4 / 2 + 2 ^ 2 % 3 end)
T("unary_chain", function() return - - 5, not not nil, #"abc" + 1, -#"abc" end)
T("string_comparison_ops", function() return "a" < "b" == true, "b" > "a" end)
T("big_function_many_locals", function() local a1, a2, a3, a4, a5, a6, a7, a8, a9, a10 = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 return a1 + a2 + a3 + a4 + a5 + a6 + a7 + a8 + a9 + a10 end)
T("shadow_param", function() local function f(x) local x = x * 2 return x end return f(4) end)
T("recursive_closure_table", function() local M = {} function M.fact(n) if n <= 1 then return 1 end return n * M.fact(n - 1) end return M.fact(6) end)
T("js_keywords_as_names", function() local class, new, var, let, const, this, function_, delete, typeof_, void, null, undefined, NaN, Infinity, arguments, yield, await, static = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18 return class + new + var + let + const + this + void + null + undefined + NaN + Infinity + arguments + yield + await + static end)
T("js_keyword_fields", function() local t = {class = 1, new = 2, constructor = 3, prototype = 4, __proto__ = 5, toString = 6, hasOwnProperty = 7} return t.class, t.new, t.constructor, t.prototype, t.__proto__, t.toString, t.hasOwnProperty end)
T("js_keyword_globals", function() undefined = 5 NaN = 6 return undefined, NaN end)
T("proto_keys_pairs", function() local t = {} t.__proto__ = 1 t.constructor = 2 local c = 0 for k in pairs(t) do c += 1 end return c, t.__proto__ end)
T("string_keys_numeric_like", function() local t = {} t["1"] = "s" t[1] = "n" t["01"] = "z" return t["1"], t[1], t["01"] end)
T("syntax_error_trailing", function() return 1 end)
