"""Сборка результата: играбельная веб-версия или страница-отчёт."""
from __future__ import annotations

import io
import json
import os
import zipfile

from .extract import (VERSION, build_game_data, check_formulas, detect_genre, evaluate_project)
from .project import ConvertError, load_project, read_archive

TEMPLATE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "template")
GAME_FILES = ["index.html", "style.css", "game.js", "i18n.js"]
REPORT_FILES = ["style.css"]

LIMITATIONS = [
    "Luau-логика НЕ транслируется. Конвертер читает только данные (таблицы значений и чистые функции-конструкторы вида "
    "`local function pet(...) return {...} end`), выполняя их в песочнице с лимитом шагов.",
    "Геймплей — готовый шаблон «pet / clicker simulator», параметризованный вашими данными (питомцы, яйца, миры, апгрейды, баланс). "
    "Если ваша игра устроена иначе (другие механики, тайкун, обби, шутер) — шаблон не подойдёт, будет страница-отчёт.",
    "Формулы экономики зашиты в шаблон (как в Pet Collector Simulator). Если в проекте есть модуль Formulas, конвертер сверяет его "
    "ответы с шаблоном и сообщает о расхождениях; остальные расчёты (Economy/Services) не проверяются.",
    "Графика — упрощённый 2D-канвас; 3D-модели, текстуры, звуки, GUI из .rbxlx не переносятся.",
    "Сервер, DataStore, лидерборд и покупки — демо (localStorage, вымышленные игроки, без платежей).",
]


def _tpl(name):
    with open(os.path.join(TEMPLATE_DIR, name), "rb") as f:
        return f.read()


def _js_assign(var, obj):
    return ("/* generated by roblox2web %s */\nwindow.%s = %s;\n" % (VERSION, var, json.dumps(obj, ensure_ascii=False, indent=1))).encode("utf-8")


class Result:
    def __init__(self):
        self.status = "error"  # game | report
        self.files = {}
        self.report = {}
        self.summary = []

    def text_report(self):
        r = self.report
        out = ["roblox2web %s — отчёт" % VERSION, "Проект: %s (%s)" % (r.get("project"), r.get("sourceKind")),
               "Жанр: %s — %s" % (r.get("genre"), r.get("genreReason")), "Итог: %s" % r.get("verdict"), ""]
        if r.get("stats"):
            out.append("Данные: " + ", ".join("%s=%s" % kv for kv in r["stats"].items()))
        if r.get("formulaCheck"):
            out.append("Сверка формул: " + r["formulaCheck"])
        if r.get("warnings"):
            out += ["", "Предупреждения:"] + ["  - " + w for w in r["warnings"]]
        out += ["", "Ограничения:"] + ["  - " + w for w in r["limitations"]]
        return "\n".join(out) + "\n"


def convert(data: bytes, filename: str = "", links=None, strict=False) -> Result:
    """Главная функция. Бросает ConvertError только для неисправимых случаев (пустой/битый архив и т.п.)."""
    files = read_archive(data, filename)
    prj = load_project(files)
    ex = evaluate_project(prj)
    genre, reason = detect_genre(prj, ex)
    res = Result()
    warnings = list(prj.warnings)
    report = {"generator": "roblox2web " + VERSION, "project": prj.name, "sourceKind": prj.kind, "genre": genre,
              "genreReason": reason, "scripts": [list(s) for s in prj.scripts], "limitations": LIMITATIONS,
              "modules": [d for d in ex.dumps if d["role"] or True][:25],
              "recognized": {role: v[0].full_name() for role, v in ex.modules.items()}}
    log = [m for m in ex.log if m][:60]

    game_data = None
    if genre == "pet-simulator":
        game_data, w2, errs = build_game_data(prj, ex)
        warnings += w2
        if errs:
            warnings += errs
            game_data = None
    if game_data is not None:
        if links:
            game_data["meta"]["links"] = links
        checked, bad, note = check_formulas(ex, game_data)
        if note:
            fc = note
        elif bad:
            fc = "РАСХОЖДЕНИЯ: " + " | ".join(bad[:6])
            warnings.append("Формулы вашего Formulas.lua отличаются от формул шаблона — поведение демо может не совпасть с игрой. " + " | ".join(bad[:3]))
        else:
            fc = "формулы %s совпали с шаблоном на тестовых значениях" % ", ".join(checked)
        report["formulaCheck"] = fc
        report["stats"] = {"pets": len(game_data["pets"]), "eggs": len(game_data["eggs"]), "zones": len(game_data["zones"]),
                           "upgrades": len(game_data["upgrades"]["list"]), "gamepasses": len((game_data["config"].get("GAMEPASSES") or {})),
                           "products": len((game_data["config"].get("PRODUCTS") or {}))}
        report["verdict"] = ("Сгенерирована играбельная веб-демо (жанр pet-simulator). Это шаблон, наполненный вашими данными, "
                             "а НЕ перевод вашего Luau-кода.")
        res.status = "game"
        for n in GAME_FILES:
            res.files[n] = _tpl(n)
        res.files["data.js"] = _js_assign("GAME_DATA", game_data)
    else:
        if strict:
            raise ConvertError("not_a_game", "Не удалось распознать игру, которую умеет собирать конвертер: %s" % reason)
        report["verdict"] = ("НЕ ИГРА: сгенерирована только страница-отчёт. %s Конвертер не транслирует произвольный Luau-код, "
                             "поэтому играбельную версию для этого проекта сделать нельзя." % reason)
        res.status = "report"
        for n in REPORT_FILES:
            res.files[n] = _tpl(n)
        res.files["index.html"] = _tpl("report.html")
        res.files["report.js"] = None  # заполним ниже
    report["warnings"] = warnings
    report["log"] = log
    res.report = report
    if res.status == "report":
        res.files["report.js"] = _js_assign("R2W_REPORT", report)
    res.files["conversion-report.json"] = json.dumps(report, ensure_ascii=False, indent=1).encode("utf-8")
    res.files["CONVERSION_REPORT.txt"] = res.text_report().encode("utf-8")
    return res


def write_dir(res: Result, outdir: str):
    os.makedirs(outdir, exist_ok=True)
    for name, blob in res.files.items():
        with open(os.path.join(outdir, name), "wb") as f:
            f.write(blob)


def make_zip(res: Result) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for name, blob in sorted(res.files.items()):
            z.writestr(name, blob)
    return buf.getvalue()
