local function check(name, cond, msg) print((cond and "OK " or "FAIL ") .. name .. (cond and "" or (": " .. tostring(msg)))) end
local v = Vector3.new(1, 2, 3)
check("v3 arith", v + Vector3.new(1, 1, 1) == Vector3.new(2, 3, 4) and v * 2 == Vector3.new(2, 4, 6) and -v == Vector3.new(-1, -2, -3) and v / 2 == Vector3.new(.5, 1, 1.5))
check("v3 dot cross", v:Dot(Vector3.new(1, 0, 0)) == 1 and Vector3.new(1,0,0):Cross(Vector3.new(0,1,0)) == Vector3.new(0,0,1))
check("v3 mag unit", math.abs(Vector3.new(3, 4, 0).Magnitude - 5) < 1e-9 and math.abs(Vector3.new(0, 5, 0).Unit.Y - 1) < 1e-9)
check("v3 lerp", Vector3.zero:Lerp(Vector3.new(10, 0, 0), 0.5) == Vector3.new(5, 0, 0))
check("v3 tostring", tostring(Vector3.new(1, 2, 3)) == "1, 2, 3", tostring(v))
check("v3 consts", Vector3.one == Vector3.new(1,1,1) and Vector3.yAxis == Vector3.new(0,1,0))
local cf = CFrame.new(1, 2, 3)
check("cf pos", cf.Position == Vector3.new(1, 2, 3) and cf.X == 1)
local r = CFrame.Angles(0, math.pi / 2, 0)
local p = r * Vector3.new(0, 0, -1)
check("cf rotate", (p - Vector3.new(-1, 0, 0)).Magnitude < 1e-6, p)
check("cf inverse", ((cf * r):Inverse() * (cf * r)).Position.Magnitude < 1e-6)
check("cf lookAt", (CFrame.lookAt(Vector3.zero, Vector3.new(0, 0, -5)).LookVector - Vector3.new(0, 0, -1)).Magnitude < 1e-6)
check("cf toObjectSpace", (cf:ToObjectSpace(CFrame.new(1, 2, 5))).Position == Vector3.new(0, 0, 2))
check("cf lerp", (CFrame.new(0,0,0):Lerp(CFrame.new(10,0,0), 0.5)).X == 5)
local c = Color3.fromRGB(255, 128, 0)
check("color3", math.abs(c.G - 128 / 255) < 1e-9 and c.R == 1)
local h, s, vv = Color3.fromHSV(0.5, 1, 1):ToHSV(); check("hsv", math.abs(h - 0.5) < 1e-6)
check("color hex", Color3.fromHex("#ff0000") == Color3.new(1, 0, 0) and Color3.new(1,0,0):ToHex() == "ff0000")
check("color lerp", Color3.new(0,0,0):Lerp(Color3.new(1,1,1), .5) == Color3.new(.5,.5,.5))
local u = UDim2.new(0.5, 10, 1, -4)
check("udim2", u.X.Scale == 0.5 and u.X.Offset == 10 and u.Y.Offset == -4 and UDim2.fromOffset(3, 4).X.Offset == 3 and UDim2.fromScale(1, 1).Y.Scale == 1)
check("udim2 add", (UDim2.fromOffset(1, 2) + UDim2.fromOffset(3, 4)).X.Offset == 4)
check("vector2", Vector2.new(3, 4).Magnitude == 5 and Vector2.new(1, 1) + Vector2.new(1, 2) == Vector2.new(2, 3))
check("enum", Enum.Material.Neon.Name == "Neon" and Enum.KeyCode.E.Value == 101 and Enum.Material.Neon == Enum.Material.Neon)
check("enum items", #Enum.EasingStyle:GetEnumItems() > 5)
check("enum typeof", typeof(Enum.Material.Neon) == "EnumItem" and typeof(Enum.Material) == "Enum")
local ti = TweenInfo.new(1, Enum.EasingStyle.Quad, Enum.EasingDirection.Out)
check("tweeninfo", ti.Time == 1 and ti.EasingStyle == Enum.EasingStyle.Quad)
local rng = Random.new(5); local a = rng:NextInteger(1, 100)
local rng2 = Random.new(5)
check("random seeded", a == rng2:NextInteger(1, 100) and a >= 1 and a <= 100)
check("random num", (function() for i = 1, 100 do local x = rng:NextNumber(); if x < 0 or x >= 1 then return false end end return true end)())
check("ns", NumberSequence.new(1).Keypoints[1].Value == 1 and NumberRange.new(1, 5).Max == 5)
check("brickcolor", BrickColor.new("Bright red").Name == "Bright red" and typeof(BrickColor.Random()) == "BrickColor")
check("region/ray", Ray.new(Vector3.zero, Vector3.new(0, 0, 1)).Direction.Z == 1)
check("rect", Rect.new(0, 0, 10, 20).Width == 10)
local dt = DateTime.fromUnixTimestamp(0); check("datetime", dt.UnixTimestamp == 0 and DateTime.now().UnixTimestamp > 1.7e9)
check("os.date", os.date("!%Y-%m-%d", 86400) == "1970-01-02", os.date("!%Y-%m-%d", 86400))
print("DONE")
